model_name: 'timeSeriesPred_double'
nn_type: 3
neurons: 80
hidLayers: 2
window_size: 3
series_length: 12
forecast: 6

direc_name: timeSeries6
trainTest_split: 0.90
trainVal_split: 0.15

epochs: 1000
init_lr: 5.e-4
patience: 30
lr_reduce_factor: 0.5
batch_size: 8




