model_name: 'trainSeries_60Min'
nn_type: 4
neurons: 1000
hidLayers: 2
window_size: 1
series_length: 720 # For input
forecast: 720 # For output
input_list:  ['relative_humidity', 'solar_radiation', 'CN2', 'temperature']
diff: -1
full_time_series: True

direc_name: OneMinResolution
trainTest_split: 0.90
trainVal_split: 0.15
num_of_examples: 3.8e4

epochs: 1000
init_lr: 1.e-3
patience: 10
lr_reduce_factor: 0.1
batch_size: 32

# Data augumentation parameters. Supported are 'jitter', 'window_warp', 'window_slice', and 'magnitude_warp 

augument_technique: 'haha'
jitter_sigma: 0.03
windowWarp_ratio: 0.3
reduce_ratio: 0.90
magnitude_sigma: 0.2
magnitude_knot: 4





