model_name: 'Test'
nn_type: 0
neurons: 1000
hidLayers: 2
series_length: 720 # For input
forecast: 360 # For output
input_list:  ['relative_humidity', 'solar_radiation', 'temperature', 'time', 'CN2']
full_time_series: True

direc_name: dataset/OneMinResolution_OneHourWindow
trainTest_split: 0.75
trainVal_split: 0.15
num_of_examples: 5.e2
num_of_examples_fixed: -1.e0
time_res: 15

epochs: 300
init_lr: 1.e-4
patience: 15
lr_reduce_factor: 0.1
batch_size: 32
isShuffle: False
saveShuffle: False
loadShuffle: False
shuffleDirec: 'shuffleInts/trainSeries_tester_6521'
zeroInput: False


