model_name: 'gruRNN_Feb28'
nn_type: 1
neurons: 50
hidLayers: 2
window_size: 3
series_length: 12

direc_name: OneHourAheadMissingData
trainTest_split: 0.90
trainVal_split: 0.15

epochs: 1000
init_lr: 1.e-3
patience: 30
lr_reduce_factor: 0.5
batch_size: 32




